### ISSUE TITLE
[Fabric] - Does not start due to "accessWidener" error on Fabric 0.14.8

### ISSUE THREAD

**Issue by Roadhog360** [OroArmor/Netherite-Plus-Mod#142]
**Describe the bug**
Lauch the game, get this crash on the Fabric error popup, game cannot start.
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod netherite-plus-mod-common
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more
```

**To Reproduce**
Install Netherite Plus and launch the game.

**Expected behavior**
The game starts

On Fabric 0.14.8, Minecraft 1.16.5. No other mods besides Fabric API installed.

**Comment by OroArmor** [comment]
You are running the forge version on fabric

**Comment by Roadhog360** [comment]
??? I clicked download on Modrinth and it said Fabric
Weird, I'll try it again
