### ISSUE TITLE
Crash on Fabric Server 0.6.1.45

### ISSUE THREAD

**Issue by shikyo13** [OroArmor/Netherite-Plus-Mod#5]
Works on single player, crashes server on startup - No crash report generated, so latest.log

[20:27:05] [main/INFO]: Loading for game Minecraft 1.16.1
[20:27:07] [main/WARN]: Warnings were found! 
 - Mod beenfo recommends mod {modmenu @ [*]}, which is missing!
 - Mod beenfo recommends mod {modupdater @ [>=1.1.7]}, which is missing!
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474c7c, also found 0.1.3+12a8474c02
[20:27:07] [main/WARN]: Mod `lightoverlay` (5.4.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[20:27:07] [main/WARN]: Mod `harvest` (1.2.12) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[20:27:07] [main/INFO]: [FabricLoader] Loading 123 mods: fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.8.9+build.203, trinkets@2.6.3, com_fasterxml_jackson_core_jackson-annotations@2.9.0, org_javacord_javacord-api@3.0.6, beenfo@1.16-fabric0.13.1-1.1, sleepvote@${version}, bbor@2.3-1.16.1, org_javacord_javacord-core@3.0.6, fabric-dimensions-v1@1.0.0+a71b305302, kibe@1.1.11-BETA, libgamerule@${version}, com_squareup_okio_okio@1.13.0, cotton-client-commands@1.0.1+1.16-rc1, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c7c, controlling@1.1.2, xaeroworldmap@1.8.0, jumpoverfences@1.16-0.0.3, tweakeroo@0.10.0-dev.20200630.023405, roughlyenoughresources@2.0.2, randompatches@1.16.1-0.0.0.4-fabric, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, waila@1.9.22, com_neovisionaries_nv-websocket-client@2.6, playerabilitylib@1.2.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, chatemotes@1.1, fabric@0.16.0+build.384-1.16.1, anvil_fix@1.1.3+build.7-1.16, netherite_plus@1.1.1, fabric-networking-v0@0.1.10+e00ecb5f02, cleancut@mc1.16-2.1-fabric, fabric-screen-handler-api-v1@1.1.0+97324d1102, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, simpledrawers@1.8.0-1.16.1, com_squareup_okhttp3_logging-interceptor@3.9.1, tacocraft@1.3.1+mc.1.16, phosphor@0.6.0+build.7, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, fabric-tool-attribute-api-v1@1.2.0+55e0cc5f02, cloth-client-events-v0@1.0.4, fabric-biomes-v1@0.2.7+059ea86602, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-language-kotlin@1.3.72+build.1, infinityfix@1.1.0, fabric-key-binding-api-v1@1.0.1+f404f3be02, cloth-config2@4.6.0, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, fabric-resource-loader-v0@0.2.6+f41e209802, malilib@0.10.0-dev.21+arne.1, org_jetbrains_kotlin_kotlin-reflect@1.3.72, worldedit@7.2.0-beta-02+d10d7d6, cardinal-components-entity@2.4.0-nightly.1.16-rc1.build.2, fabric-commands-v0@0.2.0+52d3083602, fabric-registry-sync-v0@0.3.8+7dba2d6c02, cardinal-components-base@2.4.0-nightly.1.16-rc1.build.2, lightoverlay@5.4.0, com_squareup_okhttp3_okhttp@3.9.1, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, shulkerboxtooltip@2.1.0+1.16.1, fdlink@0.4.2, org_jetbrains_annotations@17.0.0, fabric-renderer-api-v1@0.2.13+eae12eb802, parchment@1.0.2+1.15.2, inventorysorter@1.7.0-1.16, libcd@2.5.0+1.16.1, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, vanilla-hammers@1.9.0-1.16.1, fabric-containers-v0@0.1.8+045df74f02, lithium@0.5.1, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, portalcrafter@1.0.0, leadvillagers@2.1.0+mc1.16.1, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, com_electronwill_night-config_core@3.6.0, fabric-rendering-fluids-v1@0.1.8+b7084faa02, com_fasterxml_jackson_core_jackson-databind@2.9.3, fabric-lifecycle-events-v1@1.1.0+013e49d202, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, com_vdurmont_emoji-java@5.1.1, fabric-loot-tables-v1@1.0.0+386eb69e02, com_fasterxml_jackson_core_jackson-core@2.9.3, carpet@1.4.0, fabric-particles-v1@0.2.1+0a6f2a7002, gottaclimbfast@1.0, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, jankson@3.0.0+j1.2.0, wands@1.1, fabric-renderer-indigo@0.3.4+34d6c87102, mixedslab@1.16.1-fabric-1.1.0.1, com_electronwill_night-config_toml@3.6.0, roughlyenoughitems@4.10.3, fabric-item-api-v1@1.0.0+16acbe5b02, kyrptconfig@1.0.4-1.16, libgui@2.1.1+1.16.1, xaerominimap@20.18.0, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, autoconfig1u@3.2.0-unstable, harvest@1.2.12, org_json_json@20170516, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, screenshotclipboard@1.0.5, blue_endless_jankson@+, gravestones@1.4.0, appleskin@1.0.11, itemscroller@0.15.0-dev.20200630.022843, coalnugget@1.2.0.4, org_apache_logging_log4j_log4j-api@2.11.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, vanillaautomated@1.1.2, fabric-object-builders-v0@0.6.1+a2d21ddd02
[20:27:07] [main/WARN]: Mod `sleepvote` (${version}) does not respect SemVer - comparison support is limited.
[20:27:07] [main/WARN]: Mod `libgamerule` (${version}) does not respect SemVer - comparison support is limited.
[20:27:07] [main/WARN]: Mod `cleancut` (mc1.16-2.1-fabric) does not respect SemVer - comparison support is limited.
[20:27:07] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[20:27:07] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[20:27:07] [main/WARN]: Mod `coalnugget` (1.2.0.4) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[20:27:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/shiky/Desktop/1.16.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[20:27:10] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v[20:27:14] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[20:27:15] [main/INFO]: [STDOUT]: SleepVote initialized.
[20:27:15] [main/INFO]: [RER] Hello Fabric world!
[20:27:15] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[20:27:15] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[20:27:15] [main/INFO]: Discovered plugin simpledrawers:hwyla_plugin provided by simpledrawers at me.benfah.simpledrawers.plugin.hwyla.HwylaPlugin
[20:27:15] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[20:27:15] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[20:27:15] [main/INFO]: Registering plugin at me.benfah.simpledrawers.plugin.hwyla.HwylaPlugin
[20:27:16] [main/INFO]: [anvil_fix] Reloading config
[20:27:16] [main/INFO]: found fabric API, registering reload listener
[20:27:16] [main/INFO]: WorldEdit for Fabric (version 7.2.0-beta-02+d10d7d6) is loaded
[20:27:17] [main/INFO]: [STDOUT]: Config loaded!
[20:27:17] [main/INFO]: [STDOUT]: Hello Fabric world!
[20:27:17] [main/INFO]: [STDOUT]: net.minecraft.class_2248
[20:27:17] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'netherite_plus'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5272
	at com.oroarmor.netherite_plus.item.NetheritePlusModItems.registerItemsAsDamagable(NetheritePlusModItems.java:80) ~[netherite-plus-mod-1.1.1.jar:?]
	at com.oroarmor.netherite_plus.item.NetheritePlusModItems.registerItems(NetheritePlusModItems.java:75) ~[netherite-plus-mod-1.1.1.jar:?]
	at com.oroarmor.netherite_plus.NetheritePlusMod.onInitialize(NetheritePlusMod.java:11) ~[netherite-plus-mod-1.1.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5272
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at com.oroarmor.netherite_plus.item.NetheritePlusModItems.registerItemsAsDamagable(NetheritePlusModItems.java:80) ~[netherite-plus-mod-1.1.1.jar:?]
	at com.oroarmor.netherite_plus.item.NetheritePlusModItems.registerItems(NetheritePlusModItems.java:75) ~[netherite-plus-mod-1.1.1.jar:?]
	at com.oroarmor.netherite_plus.NetheritePlusMod.onInitialize(NetheritePlusMod.java:11) ~[netherite-plus-mod-1.1.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more

**Comment by OroArmor** [comment]
Thanks, i just saw another person with this same issue, im going to point them all at the same place so it is easier for me to start (i found the point of breaking)

**Comment by OroArmor** [comment]
issue is https://github.com/OroArmor/Netherite-Plus-Mod/issues/6
